# Generated by Django 4.2.16 on 2024-11-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productcategory_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_id',
        ),
    ]
