# Generated by Django 4.2.16 on 2024-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productcategory_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
