# Generated by Django 5.1.3 on 2024-11-27 16:28

from django.db import migrations, models

def fix_foreign_key(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    for product in Product.objects.all():
        product.category_name_id = product.category_name.category_id  # Fix foreign key to category_id
        product.save()

class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_productcategory_category_id'),
    ]

    operations = [
        migrations.RunPython(fix_foreign_key),
    ]